### ISSUE TITLE
Capture images from my local camera

### ISSUE THREAD

**Issue by ciaoamigoschat** [jellyfish-dev/react-native-client-sdk#18]
Hello everyone, I was wondering if it's possible to capture images from my local camera while I'm live streaming. Does anyone have experience with this? If so, could you kindly share how it can be done? Thanks in advance!

**Comment by incubo4u** [comment]
Hi @ciaoamigoschat
Right now, the ability to capture images from the local camera while live streaming might be a bit tricky due to the way we manage the camera capturer within our project. Currently, it's not directly exposed for external access.
We're actively working on changing this
